---
api_key:
api_url:
notify_from: test@example.com
notify_to: notify-to@example.com
notify_offset: 1800 # 30minutes = 1800seconds
max_daily_offline: 5400 # 90 minutes
departments:
  your_department_name:
    departmentid: 111111t
    online_statuses: T,P
