---
api_key:
api_url:
notify_from: test@example.com
notify_to: notify-to@example.com
notify_offset: 1800 # 30minutes = 1800seconds
departments:
  chat_support_department:
    departmentid: 5965d21e
    online_statuses: T,P